server:
  port: 8080

eureka:
  client:
  register-with-eureka: false
  fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-customer
          uri: lb://service-customer
          predicates:
            - Path=/customers/**
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/products/**
        - id: service-shopping
          uri: lb://service-shopping
          predicates:
            - Path=/invoices/**